services:
  embedding_api:
    build:
      context: ./embeddings
      dockerfile: Dockerfile
    container_name: embedding_api
    ports:
      - "8001:8001"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8001/.well-known/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - weaviate_net
  
  processor_api:
    build:
      context: ./document-processor
      dockerfile: Dockerfile
    container_name: processor_api
    ports:
      - "8002:8002"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8002/.well-known/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - weaviate_net

  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.32.9
    container_name: weaviate
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      ENABLE_MODULES: "text2vec-transformers"
      TRANSFORMERS_INFERENCE_API: "http://embedding_api:8001"
      DEFAULT_VECTORIZER_MODULE: "text2vec-transformers"
    depends_on:
      embedding_api:
        condition: service_healthy
      processor_api:
        condition: service_healthy
    volumes:
      - weaviate_data:/var/lib/weaviate
    networks:
      - weaviate_net

volumes:
  weaviate_data:

networks:
  weaviate_net:
    driver: bridge