james = {
    "DocumentParentChunk": [
        {
            "_additional": {
                "answer": {
                    "certainty": None,
                    "endPosition": 0,
                    "hasAnswer": False,
                    "property": None,
                    "result": None,
                    "startPosition": 0,
                },
                "certainty": 0.6005778908729553,
                "id": "72a4fcef-4de3-4800-99c3-9f378d7f29f8",
                "score": "0",
            },
            "chunk_text": "Northrop Grumman. .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 71\n\t\nTeledyne Brown Engineering . .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 72\n\t\nUnited Launch Alliance. .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 73\nAdditional Resources . .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 74\n\t\nUnderstanding SLS: Infographics. .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 75\n\t\nAcronym List. .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 83\n4",
            "user_id": "smaueltown@gmail.com",
        },
        {
            "_additional": {
                "answer": {
                    "certainty": None,
                    "endPosition": 0,
                    "hasAnswer": False,
                    "property": None,
                    "result": None,
                    "startPosition": 0,
                },
                "certainty": 0.600376695394516,
                "id": "d2b6fb76-0ce7-4d69-88a2-f185f51784d0",
                "score": "0",
            },
            "chunk_text": "SLS Overview. .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 12\n\t\nSLS Design: Chosen from Thousands of Options. .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . 13\n\t\nCommon Elements and Evolvability. .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 15\n\t\n\t\nMore Powerful Rockets for Future Missions . .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 17\n\t\nSLS Vehicle-Level Testing. .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 19\n\t\nSuper Heavy Lifting on the Ground: SLS Transportation, Logistics, and Pathfinders. .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . 22\n\t\nExterior Features of SLS. .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 25\n\t\n\t\nThermal Protection System. .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 25\n\t\n\t\nLivery and Photogrammetric Markings . .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 26\t\n\t\n\t\nInstrumentation and Vehicle Telemetry. .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 27\nThe Role of SLS in Launching Artemis I. .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 28\n\t\nArtemis I Secondary Payloads. .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 30",
            "user_id": "smaueltown@gmail.com",
        },
        {
            "_additional": {
                "answer": {
                    "certainty": None,
                    "endPosition": 0,
                    "hasAnswer": False,
                    "property": None,
                    "result": None,
                    "startPosition": 0,
                },
                "certainty": 0.6003571450710297,
                "id": "05ef75bb-c6a6-4860-a7cf-3e55f19831a5",
                "score": "0",
            },
            "chunk_text": "The Elements of SLS. .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 34\n\t\nCore Stage. .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 35\n\t\n\t\nManufacturing, Test, and Checkout. .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 39\n\t\n\t\nCore Stage Fun Facts. .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 41 \n3",
            "user_id": "smaueltown@gmail.com",
        },
        {
            "_additional": {
                "answer": {
                    "certainty": None,
                    "endPosition": 0,
                    "hasAnswer": False,
                    "property": None,
                    "result": None,
                    "startPosition": 0,
                },
                "certainty": 0.6002910733222961,
                "id": "6f13122a-986f-4a67-a574-cbf306163e54",
                "score": "0",
            },
            "chunk_text": "Manufacturing, Test, and Checkout. .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 58\n\t\nSLS Avionics and Software. .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 59\nManagement Roles and Facilities. .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 60\n\t\nMarshall Space Flight Center. .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 61\n\t\n\t\nUnique Test Facilities. .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 61\n\t\n\t\nSupporting Launch Operations . .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 62\n\t\nMichoud Assembly Facility. .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 64\n\t\nStennis Space Center. .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 66\nIndustry Partners. .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 68\n\t\nAerojet Rocketdyne . .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 69\n\t\nBoeing. .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 70",
            "user_id": "smaueltown@gmail.com",
        },
        {
            "_additional": {
                "answer": {
                    "certainty": None,
                    "endPosition": 0,
                    "hasAnswer": False,
                    "property": None,
                    "result": None,
                    "startPosition": 0,
                },
                "certainty": 0.6002685129642487,
                "id": "cd7c917c-6b82-4c68-9e3b-19e1a6ddff82",
                "score": "0",
            },
            "chunk_text": "TABLE OF CONTENTS\nTable of Contents\nFrom the SLS Program Manager and Chief Engineer. .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 5\nIntroduction . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 6\nSLS Quick Facts . .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 7\n\t\nNASA’s Block 1 Space Launch System by the Numbers. .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . 8\n\t\n\t\nSLS Vehicle. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 8\n\t\n\t\nCore Stage. .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 8\n\t\n\t\nRS-25 Engines. .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 8\n\t\n\t\nSolid Rocket Boosters. .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 9\n\t\n\t\nInterim Cryogenic Propulsion Stage (Upper Stage). .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . 9\n\t\n\t\nLaunch Vehicle Stage Adapter. .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 9\n\t\n\t\nOrion Stage Adapter. .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 9\n\t\n\t\nSecondary payloads. .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 10",
            "user_id": "smaueltown@gmail.com",
        },
        {
            "_additional": {
                "answer": {
                    "certainty": None,
                    "endPosition": 0,
                    "hasAnswer": False,
                    "property": None,
                    "result": None,
                    "startPosition": 0,
                },
                "certainty": 0.5998210906982422,
                "id": "8925f816-0c2e-4cc7-a9ad-fb6872ea33c9",
                "score": "0",
            },
            "chunk_text": "CONTINUED TABLE OF CONTENTS\n\t\nRS-25 Engines . .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 42\n\t\n\t\nManufacturing, Test, and Checkout. .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 44\n\t\n\t\nFlight History of Artemis I RS-25 Engines. .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 45\n\t\n\t\nRS-25 Fun Facts . .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 46\n\t\nSolid Rocket Boosters . .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 47\n\t\n\t\nManufacturing, Test, and Checkout. .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 50\n\t\n\t\nFlight History of the SLS Booster Structures. .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 52\n\t\n\t\nSolid Rocket Boosters Fun Facts. .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 53\n\t\nIntegrated Spacecraft/Payload Element. .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 54\n\t\n\t\nInterim Cryogenic Propulsion Stage. .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 55\n\t\n\t\nLaunch Vehicle Stage Adapter. .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 56\n\t\n\t\nOrion Stage Adapter. .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 57",
            "user_id": "smaueltown@gmail.com",
        },
        {
            "_additional": {
                "answer": {
                    "certainty": None,
                    "endPosition": 0,
                    "hasAnswer": False,
                    "property": None,
                    "result": None,
                    "startPosition": 0,
                },
                "certainty": 0.5889538526535034,
                "id": "7724c408-1676-4705-bc92-169ae72e6669",
                "score": "0",
            },
            "chunk_text": "–\t Testing communication systems.\n–\t Core stage/ICPS staging and core stage \nocean impact.\n–\t ICPS operations, including steering, engine \nstart and shutdown, perigee raise and TLI \nengine burns, and disposal maneuver.\n–\t Orion/ICPS staging.\n–\t Secondary payload deployment.Image of SLS core stage liquid hydrogen tank structural test article\n29\nTechnicians installed the liquid hydrogen tank structural test article in its \ntest stand at Marshall at night when winds were minimal.",
            "user_id": "smaueltown@gmail.com",
        },
        {
            "_additional": {
                "answer": {
                    "certainty": None,
                    "endPosition": 0,
                    "hasAnswer": False,
                    "property": None,
                    "result": None,
                    "startPosition": 0,
                },
                "certainty": 0.5837136507034302,
                "id": "aaaff336-8465-4c11-bd68-c857e59666b1",
                "score": "0",
            },
            "chunk_text": "Launch Complex 39B to accurately understand how liquid and gases \nflowing during launch can cause various kinds of waves at the launch pad.Image of a five percent scale model of SLS in acoustic testing\nA five-percent scale model of SLS undergoes acoustic testing in 2014 at \nMarshall.",
            "user_id": "smaueltown@gmail.com",
        },
        {
            "_additional": {
                "answer": {
                    "certainty": None,
                    "endPosition": 0,
                    "hasAnswer": False,
                    "property": None,
                    "result": None,
                    "startPosition": 0,
                },
                "certainty": 0.5803441405296326,
                "id": "f6f62662-9d32-42d1-84ac-e420589bb973",
                "score": "0",
            },
            "chunk_text": 'THE ELEMENTS OF SLS\nCORE STAGE MANUFACTURING, TEST,  \nAND CHECKOUT\nLikewise, avionics and flight software, the “brains” of SLS, \nwere developed, tested, and virtually flown thousands of \ntimes at Marshall\'s Integrated Avionics and Software and \nSystems Integration laboratories before the flight hardware \nand software were installed in the Artemis I core stage.\nIn addition, Artemis I core stage suppliers tested individual \ncomponents before shipping to Michoud. Once at Michoud, \nBoeing tested the components and functions before \ninstalling them on the core stage. The completed stage \nunderwent basic electrical and pneumatic testing before \nshipment to Stennis for the Green Run test campaign. \n“Green run” describes the first operational test of a new \ncomponent. \nAt Stennis, teams from Boeing, SLS, and Stennis used the \nGreen Run test series of progressively more flight-like tests \nto activate stage systems, culminating in a hot fire of the \nengines that simulated launch and flight of the Artemis I \ncore stage. \nBeginning in early 2020, the Artemis I core stage was \ninstalled in the B-2 test stand, used previously to support \nSaturn and shuttle propulsion tests. During the year it was \nsubjected to a series of nine major Green Run tests:  \n–\tModal (vibration).\n–\tCore stage avionics power on and checkout.\n–\tSafing checks (how to shut down all core stage \nsystems in case of an anomaly).\n–\tMain propulsion system (stage propellant valves and \nducts) and RS-25 leak checks and functional tests. \n–\tHydraulic and thrust vector control (engine steering) \ncheckout.\n–\tSimulated countdown.\n–\tCountdown and wet dress rehearsal (full stage \noperation, including flowing propellants to the engines \nfor chilldown).\n–\tCountdown and hot fire (limited duration test up to \nthrust vector control gimbal).\n–\tCountdown and hot fire (full test of the stage including \nengines in flight-like operation).\nAt the end of testing, the stage was inspected and \nrefurbished  before shipping to Kennedy onboard NASA’s \nbarge Pegasus.\n40Image of the core stage Green Run hot fire.\nEight major "Green Run" tests at Stennis of the Artemis I core stage and RS-25 engines culminated in a full-duration hot firing, the largest test of liquid-fueled \nengines since the Apollo Program.',
            "user_id": "smaueltown@gmail.com",
        },
        {
            "_additional": {
                "answer": {
                    "certainty": None,
                    "endPosition": 0,
                    "hasAnswer": False,
                    "property": None,
                    "result": None,
                    "startPosition": 0,
                },
                "certainty": 0.5733886361122131,
                "id": "9a687023-14d6-422f-a7f1-e4790d67695e",
                "score": "0",
            },
            "chunk_text": "facilities at those centers. Image of NASA F/A-18 aircraft testing SLS software\nIn 2013, NASA conducted a series of F/A-18 research flights to test SLS \nprototype software, including the previously adaptive augmenting control \ncomponent. Adaptive augmenting contol benefits total attitude control and \nincreases flight control system performance when excessive tracking error \nis present and decreases responsiveness to undesirable frequency content. \nIt expands the envelope under which the flight control system is capable of \nsafely flying the vehicle.Image of the Systems Integration Lab at Marshall Space Flight Center\nThe Systems Integration Lab at Marshall includes flight computers and \navionics functionally identical to the core stage avionics to test all systems \nprior to flight.",
            "user_id": "smaueltown@gmail.com",
        },
        {
            "_additional": {
                "answer": {
                    "certainty": None,
                    "endPosition": 0,
                    "hasAnswer": False,
                    "property": None,
                    "result": None,
                    "startPosition": 0,
                },
                "certainty": 0.5720280110836029,
                "id": "0d3a6f22-25f1-4586-8751-c951cacfba5b",
                "score": "0",
            },
            "chunk_text": 'SLS OVERVIEW\nSLS VEHICLE-LEVEL TESTING\n20\nTEN ITCO TESTS TO PREPARE FOR FLIGHT:\n1.\t Modal Tests: These tests characterize vehicle \ndynamics and include booster push/pull testing, \na modal tap test, and integrated modal testing on \nthe mobile launcher and crawler-transporter with \nOrion stage adapter test article and Orion mass \nsimulator using hydraulic shakers and calibrated \nhammers.\n2.\t Interface Verification Test: Also performed with \nthe Orion stage adapter test article and the Orion \nsimulator "as well as" with the Artemis I Orion, \nthis test verifies functionality and interoperability \nof SLS-to-Orion interfaces.\n3.\t Communications End-to-End Test: This critical \ntest validates communications between the \nvehicle and tracking network.\n4.\t Umbilical Release and Retract Test: \nTesting the timing of booster arming and firing \nand the command for umbilical release.\n5.\t Vehicle Assembly Building Project-Specific \nEngineering Test: Element-level testing of SLS in \nthe Vehicle Assembly Building.\n6.\t Countdown Sequence Test: Training the launch \nteam with Artemis I flight hardware in the loop.\n7.\t Flight Safety System: Rehearsal for pre- \nand post-wet dress and ordnance and flight \ntermination system communications.\n8.\t Dynamic Rollout Test: Rolling the vehicle\nfrom the Vehicle Assembly Building to Launch \nComplex 39B and back to compare actual loads \nto analytical models.\n9.\t Pad Project-Specific Engineering Test: At the \nlaunch pad, testing radio frequency; guidance, \nnavigation, and control; and performing final \nordnance tests.\n10.\tWet Dress Rehearsal: Testing propellant \nloading procedures, structural response, thermal \nconditioning and loading procedures; vehicle \ncontrol system; avionics and software checkout; \nelectromagnetic interference; guidance and \nnavigation; main propulsion system; and engine \nand booster nozzle steering.Image of SLS rocket stacked for modal testing\nModal testing underway in High Bay 3 inside the Vehicle Assembly Building \nat Kennedy, using the Orion stage adapter structural test article and the \nmass simulator for Orion. The test hardware articles have the same weight \nand mass characteristics as their respective flight components.',
            "user_id": "smaueltown@gmail.com",
        },
        {
            "_additional": {
                "answer": {
                    "certainty": None,
                    "endPosition": 0,
                    "hasAnswer": False,
                    "property": None,
                    "result": None,
                    "startPosition": 0,
                },
                "certainty": 0.5660411715507507,
                "id": "913983db-0b96-4bff-b7b7-3a5b74a68f6a",
                "score": "0",
            },
            "chunk_text": "cryogenic spill. Image of the core stage in the B-2 Test Stand at Stennis Space Center\nNASA Stennis provides unique facilities for testing SLS RS-25 engines and controllers.",
            "user_id": "smaueltown@gmail.com",
        },
        {
            "_additional": {
                "answer": {
                    "certainty": None,
                    "endPosition": 0,
                    "hasAnswer": False,
                    "property": None,
                    "result": None,
                    "startPosition": 0,
                },
                "certainty": 0.5572770833969116,
                "id": "fa302e95-2d05-49c8-8dcb-997f485e7dc6",
                "score": "0",
            },
            "chunk_text": "THE ELEMENTS OF SLS\nCORE STAGE\nThe forward skirt is located at the top of the core stage. It \nconnects the core stage to the Integrated Spacecraft/Payload \nElement. The aluminum isogrid structure is 27.6 ft. (8.4 m) in \ndiameter and 10.4 ft. (3.2 m) tall. It houses the majority of the \nvehicle’s avionics and has connections to launch pad utility \numbilicals, the vehicle stabilization system that helps secure \nSLS to the mobile launcher, access doors, vent system, \npressurant lines, and antennas.\nThe main propulsion system in the core stage consists of the \nducts, valves, and other equipment that supply and control \nthe flow of liquid hydrogen and liquid oxygen propellants, as \nwell as gaseous helium and nitrogen pressurants for valve \nactuation and line/volume purges. To accomplish those \nfunctions, the main propulsion system has four subsystems: \n–\tLiquid oxygen.\n–\tLiquid hydrogen.\n–\tPressurization.\n–\tPneumatics supplied by ground systems prior to launch.\nMajor drivers in the design of the main propulsion system \nincluded the main propellant tank configuration, main \nengine configuration, reliability and affordability, mission \nrequirements, and component mounting. For instance, the \nmain propulsion system flow rates and interfaces were \ndesigned around the RS-25 configuration and the need to \nsupply propellants to the engines under temperature and \npressure conditions required by the engines. The orientation \nof the engine hydrogen and oxygen feedlines in the engine \nsection determined the feed system layout for the main \npropulsion system.Image of the liquid oxygen tank\nThe liquid oxygen tank being manufactured for the Artemis I flight at Michoud.Image of the core stage forward skirt\nThe core stage forward skirt contains the flight computers for the Block 1 \nSLS rocket.Image of the core stage at Michoud Assembly Facility\nConnecting feedlines and other external components to the fully assembled \nArtemis I core stage at Michoud.\n38",
            "user_id": "smaueltown@gmail.com",
        },
        {
            "_additional": {
                "answer": {
                    "certainty": None,
                    "endPosition": 0,
                    "hasAnswer": False,
                    "property": None,
                    "result": None,
                    "startPosition": 0,
                },
                "certainty": 0.5568126440048218,
                "id": "30d8ca61-e380-451d-a518-d32789bff66b",
                "score": "0",
            },
            "chunk_text": "MANAGEMENT ROLES AND FACILITIES\nSTENNIS SPACE CENTER\nThe stand extends 58 ft. (17.7 m) below ground and 158 ft. \n(48.2 m) above ground. It can withstand rocket engine thrust \nup to about 1.1 million lbs. (4,893 kN) of force; the thrust \nlimit is known as the maximum dynamic load.\nThe B Test Complex at Stennis features a dual-position, \nvertical-firing test stand designated B-1/B-2, built in the \n1960s. The B-1 Test Stand is designed for single-engine \ntesting. The B-2 Test Stand is built to accommodate \nrocket stage testing. The B-2 Test Stand underwent major \nrefurbishment and modifica¬tion to conduct the SLS Artemis \nI core stage Green Run test series to ready the stage for \nintegration and flight. \nThe B-1/B-2 Test Stand is anchored in the ground with 144 \nft. (43.9 m) of steel and concrete. As constructed, the soft \ncore of the B-2 Test Stand was about 290 ft. (88.4 m) tall. \nThe new steel superstructure added for testing SLS extends \nthat height to almost 350 ft. (106.7 m), ranking the stand as \none of the tallest structures in the state of Mississippi. \nStennis test stands are linked by a 7.5-mile canal system \nused for transporting rocket stages and liquid propellants. \nSupport facilities for Stennis test stands include a test \n67\ncontrol center for each complex; data acquisition facilities; \na large High Pressure Gas Facility to supply pressurized \nnitrogen, helium, hydrogen, and air; an electrical generation \nplant that provides power for engine tests to avoid potential \ndisruptions in the power grid; and a High-Pressure Industrial \nWater Facility that features large diesel pumps, as well as \na new electric pump, and a 66 million gal. (249,837,178 L) \nreservoir.\nThe main derrick crane atop the B-2 Test Stand was \nextended 50 ft. (15.2 m) with an increased load rating of 195 \ntons (177 t) to lift the SLS core stage, which is larger and \nheavier than the earlier Saturn V stages. More than 32,500 \n5/32-inch holes drilled in the B-2 Test Stand flame deflector \ndirect more than 240,000 gal. (908,499 L) of water a minute \nto cool engine exhaust during a test. Another 92,000 gal. \n(348,258 L) of water per minute is sprayed through 92 \nnozzles to provide vibro-acoustic suppression protection to \nthe core stage during testing. More than 100 water nozzles \nare arrayed across the test stand to provide a curtain of \nwater over the length of the core stage and across the \nfacility, if needed, to prevent damage in the event of a fire or",
            "user_id": "smaueltown@gmail.com",
        },
        {
            "_additional": {
                "answer": {
                    "certainty": None,
                    "endPosition": 0,
                    "hasAnswer": False,
                    "property": None,
                    "result": None,
                    "startPosition": 0,
                },
                "certainty": 0.5565992593765259,
                "id": "464bca78-3545-49e8-b8c5-7189c9c27f9f",
                "score": "0",
            },
            "chunk_text": "MANAGEMENT ROLES AND FACILITIES\nMICHOUD ASSEMBLY FACILITY\nAt Michoud, six major multi-function assembly/welding tools developed for SLS have resulted in a greater than 80 percent \nreduction in tooling from shuttle external tank production. This reduced tooling also minimizes hardware handling, reducing \ncomplex hardware lifting operations by more than 70 percent. \nThe new tools in NASA’s rocket factory include:\n–\tThe Circumferential Dome Weld Tool, which performs circumferential friction-stir welds in the production of \ndome assemblies for the SLS core stage cryogenic tanks.\n–\tThe Gore Weld Tool performs vertical conventional friction stir welds in the production of gore assemblies for the SLS \ncore stage tanks. (Gores are preformed aluminum alloy dome segments that are welded together to make the dome).\n–\tThe Circumferential Dome Weld and Gore Weld tools are special tooling for the Enhanced Robotic Weld Tool, which is \nused to make dome components for SLS.\n–\tThe Vertical Weld Center is a friction-stir-weld tool for wet and dry structures on the SLS core stage. It welds barrel \npanels together to produce whole barrels for the two pressurized tanks, the intertank, the forward skirt, and the engine \nsection. It stands about three stories tall and weighs 150 tons (136 t).\n–\tThe Segmented Ring Tool uses a friction-stir-weld process to produce segmented support rings for the SLS core stage; \nthe rings connect and provide stiffness between domes and barrels.\n–\tThe Vertical Assembly Center is where domes, rings, and barrels are joined to complete the tanks or dry structure \nassemblies. The tool also performs nondestructive evaluation on the completed welds. This tool measures 170 ft. \n(51.8 m) tall and 78 ft. (23.7 m) wide and is one of the world's largest welding tools.Image of gore weld tool at Michoud Assembly Facility\nThe gore weld tool at Michoud is used to weld domes for the SLS core stage propellant tanks.\n65",
            "user_id": "smaueltown@gmail.com",
        },
        {
            "_additional": {
                "answer": {
                    "certainty": None,
                    "endPosition": 0,
                    "hasAnswer": False,
                    "property": None,
                    "result": None,
                    "startPosition": 0,
                },
                "certainty": 0.5548189878463745,
                "id": "c1afd599-0fe9-46e6-8b93-07ba33c44bf0",
                "score": "0",
            },
            "chunk_text": "INDUSTRY PARTNERS\nTELEDYNE BROWN ENGINEERING\nTeledyne Brown Engineering\nTeledyne Brown Engineering, based in Huntsville, \nAlabama, has been a leader in innovative products, \nsystems, integration, operation, and manufacturing \nfor the space industry for more than 65 years. \nTeledyne Brown provides engineering, technical \nsupport, and hardware for the launch vehicle \nstage adapter. The launch vehicle stage adapter is \nmanufactured using the friction-stir welding tools \nin the Advanced Weld Facility at Marshall. It is the \nlargest piece of the current SLS configuration to be \nbuilt at Marshall. In addition to the Artemis I adapter, \nTeledyne Brown Engineering also delivered the \nlaunch vehicle stage adapter structural test article in \n2016 for the Integrated Structural Test.Image of the launch vehicle stage adapter stacked on the SLS rocket\nTeledyne Brown Engineering is the lead contractor for the launch vehicle stage adapter \nthat has a pneumatically activated frangible joint that separates it and the core stage \nfrom the ICPS, Orion stage adapter, and Orion during flight.\n72\n\nINDUSTRY PARTNERS\nUNITED LAUNCH ALLIANCE\nUnited Launch Alliance\nULA is working collaboratively with Boeing to \ndevelop the 5-m ICPS for Artemis I, II, and III. \nThe ICPS stages are manufactured in ULA’s \nDecatur, Alabama, manufacturing facility. The \nICPS stage is a modified version of the ULA 5-m \nDelta Cryogenic Second Stage, which has flown \n24 times with 100 percent mission success.\nWith more than a century of combined heritage, \nULA is the nation’s most experienced and \nreliable launch service provider. ULA has \nsuccessfully delivered more than 140 missions \nto orbit that aid meteorologists in tracking \nsevere weather, unlock the mysteries of our solar \nsystem, provide critical capabilities for troops \nin the field, deliver cutting-edge commercial \nservices, and enable GPS navigation.\nULA’s program management, engineering, test, \nand mission support functions are headquartered \nin Denver, Colorado. Manufacturing, assembly, \nand integration operations are located at \nDecatur, Alabama, and Harlingen, Texas. Launch \noperations are located at Cape Canaveral Space \nForce Station, Florida, and Vandenberg Space \nForce Base, California.Image of the interim cryogenic propulsion stage and United Launch Alliance team\nULA supplies the ICPS, which is based on the Delta Cryogenic Second Stage, for the SLS \nBlock 1 rocket. \n73\n\n## ADDITIONAL \nRESOURCES\n \nADDITIONAL RESOURCES \n74",
            "user_id": "smaueltown@gmail.com",
        },
        {
            "_additional": {
                "answer": {
                    "certainty": None,
                    "endPosition": 0,
                    "hasAnswer": False,
                    "property": None,
                    "result": None,
                    "startPosition": 0,
                },
                "certainty": 0.5539032220840454,
                "id": "b0552d8d-82cd-4783-b5d1-b43e3a23c124",
                "score": "0",
            },
            "chunk_text": "THE ELEMENTS OF SLS\nINTERIM CRYOGENIC PROPULSION STAGE\nThe 45-ft. (13.7 m)-tall, 16.7-ft. (5.1 m)\n-diameter ICPS is a modified Delta Cryogenic \nSecond Stage, a proven upper stage used \non ULA’s Delta IV family of launch vehicles. \nULA builds the ICPS at its rocket factory \nin Decatur, Alabama. After completion, it’s \nshipped to ULA’s Delta Operations Center \nat Cape Canaveral Space Force Station on \nULA's R/S Rocketship cargo ship for final \ncheckout prior to stacking in the Vehicle \nAssembly Building.\nModifications to the Delta stage for the Block \n1 SLS missions include lengthening the \nliquid hydrogen tank by 18.4 in. (46.7 cm), \nadding a second hydrazine bottle for attitude \ncontrol, a new navigation system, Orion \nand launch vehicle stage adapter electrical \nand mechanical interfaces, a modified \nInterim Cryogenic Propulsion StageIllustration of SLS with integrated spacecraft/payload element highlighted\nliquid hydrogen vent and relief valve, an RL10 in-flight \nhelium injector purge to support engine restart, and RL10 \nqualification to SLS environments.\nThe stage is powered by liquid hydrogen and liquid oxygen, \nfeeding a single Aerojet Rocketdyne RL10B-2 engine \nproducing 24,750 lbs. (110 kN) of thrust. The RL10 has \nbeen in use more than 50 years to launch numerous military, \ngovernment, and commercial satellites into orbit and send \nspacecraft to every planet in the solar system. \nAPPROXIMATE TIMELINE OF ICPS EVENTS DURING THE ARTEMIS I FLIGHT\nMajor ICPS event\nApproximate time post-launch (T-0)\nICPS/core stage separation\nT-0 + 8 minutes and 30 seconds\nICPS coast to near apogee\nT-0 + 8 minutes and 20 seconds to 51 minutes\nICPS perigee raise burn\nT-0 + 50 minutes and 30 seconds to 51 minutes and 20 seconds\nParking orbit coast\nT-0 + 51 minutes to 1 hour and 36 minutes\nICPS TLI burn\nT-0 + 1 hour and 37 minutes to 1 hour and 55 minutes\nCoast to Orion separation from ICPS\nT-0 + 1 hour and 55 minutes to 2 hours and 5 minutes\nPost-separation coast\nT-0 + 2 hours and 5 minutes to 3 hours and 45 minutes\nICPS disposal maneuver to heliocentric orbit\nT-0 + 3 hours and 45 minutes to 3 hours and 48 minutes \n*Numbers based on 2021 mission analysis as this guide was in development and will vary based on season, launch date, and time. Numbers are \napproximated to meet security, export control, and proprietary requirements.\nFor the Artemis I mission, the ICPS will perform three burns: \n–\tA perigee burn to circularize Orion’s orbit.",
            "user_id": "smaueltown@gmail.com",
        },
        {
            "_additional": {
                "answer": {
                    "certainty": None,
                    "endPosition": 0,
                    "hasAnswer": False,
                    "property": None,
                    "result": None,
                    "startPosition": 0,
                },
                "certainty": 0.5533797442913055,
                "id": "c7c7cf70-970d-4f5d-874f-ca2e2785e1cc",
                "score": "0",
            },
            "chunk_text": "MANAGEMENT ROLES AND FACILITIES\nSTENNIS SPACE CENTER\nStennis Space Center\nAs the nation’s largest propulsion test site, Stennis plays a \nmajor role in testing for SLS, just as it did for Saturn rockets \nand space shuttle vehicles.\nThe Fred Haise Test Stand was used to conduct multiple \ntests of RS-25 developmental engines to ensure the \nmodified flight engines will operate to SLS requirements and \nenvironments. It was also used to Green Run test two new \nRS-25 engines, as well as new engine controllers for all 16 \nshuttle engines transferred from the Space Shuttle Program. \nThe hot fire tests for the new engines and controllers also \nwere conducted on Stennis’s Fred Haise Test Stand. In \n2021, NASA began using the stand to test RS-25 engines \nwith newly designed parts made with advanced technology, \nsuch as additive manufacturing or 3D printing, for a new \ngeneration  of engines for the fifth SLS flight and beyond.  \nNewer engines will have the same high performance as the \nupgraded engines used for early Artemis missions, but with \nanticipated manufacturing cost savings of more than 30 \npercent.\nThe Fred Haise Test Stand is a single-position, vertical-firing \nfacility, which means that it can accommodate one rocket \nengine at a time and that engines are fired in an upright \nposition with thrust directed downward. The stand was \nconstructed from December 1964 to February 1967. The \nfirst test of an RS-25 rocket engine was conducted on the \nFred Haise Test Stand on January 9, 2015. On April 4, 2019, \nStennis completed testing of all 16 RS-25 main engines that \nwill help launch the first four SLS missions.Image of test stands at Stennis Space Center\nNASA Stennis provides unique facilities for testing SLS RS-25 engines and \ncontrollers. The B Complex, foreground, was used for Green Run testing \nthe SLS core stage.\n66",
            "user_id": "smaueltown@gmail.com",
        },
        {
            "_additional": {
                "answer": {
                    "certainty": None,
                    "endPosition": 0,
                    "hasAnswer": False,
                    "property": None,
                    "result": None,
                    "startPosition": 0,
                },
                "certainty": 0.549637496471405,
                "id": "e9e77212-53c2-4d67-9376-f593b946e7a2",
                "score": "0",
            },
            "chunk_text": "UNDERSTANDING SLS: INFOGRAPHICS\nUnderstanding SLS: Infographics\n75\nIn addition to the Quick Facts in the front of this document, \nselected SLS infographics below will help you understand \nSLS and its unique capabilities to enable continuous, ongoing \nhuman exploration of the Moon through the Artemis program. \nAdditional infographics describing SLS design, capabilities, \ntesting, and more are available on the SLS web site at \nhttps://www.nasa.gov/exploration/systems/sls/multimedia/\ninfographics.htmlAn SLS infographic titled A Bolder Mission\n\nUNDERSTANDING SLS: INFOGRAPHICSAn infographic explaining the Integrated Spacecraft/Payload Element\n76\n\n## UNDERSTANDING SLS: INFOGRAPHICS\n77\n\n## UNDERSTANDING SLS: INFOGRAPHICS\n78\n\n## UNDERSTANDING SLS: INFOGRAPHICS\n79\n\n## UNDERSTANDING SLS: INFOGRAPHICS\n80\n\n## UNDERSTANDING SLS: INFOGRAPHICS\n81\n\n## UNDERSTANDING SLS: INFOGRAPHICS\n82\n\n83\nTABLE OF CONTENTS\nACRONYM LIST\nACRONYM\t\nDEFINITION\nAES.................. Advanced Exploration Systems\nBFF................... Booster Fabrication Facility\nEGS.................. Exploration Ground Systems\nESA.................. European Space Agency\nEUS.................. Exploration Upper Stage\nGSE.................. Ground Support Equipment\nICPS................. Interim Cryogenic Propulsion Stage\nISS....................International Space Station\nITCO................. Intergrated Test and Check Out\nJAXA................ Japanese Aerospace Exploration Agency\nLAS.................. Launch Abort System\nLCC.................. Launch Control Center\nLVSA................. Launch Vehicle Stage Adapter\nMax Q.............. Maximum Dynamic Pressure\nMECO.............. Main Engine Cutoff\nMPLM............... Multi-Purpose Logistics Module\nOSA.................. Orion Stage Adapter\nPBAN............... Polybutadiene Acrylonitrile\nRPSF................ Rotation, Processing, and Surge Facility\nSESC................ SLS Engineering Support Center\nSLS.................. Space Launch System\nSMD................. Science Mission Directorate\nSSME............... Space Shuttle Main Engine\nSTS.................. Space Transporation System\nTLI.................... Trans-Lunar Injection\nULA.................. United Launch Alliance\nFor more information about SLS, visit: \nhttp://www.nasa.gov/artemis \nhttp://www.nasa.gov/sls \nhttp://www.twitter.com/NASA_SLS \nhttp://www.facebook.com/NASASLS \nhttp://www.instagram.com/exploreNASA\nLINKSSilhouette image of the SLS rocket with the bright moon in the background.\n\n## NOTES\n\n## NOTES",
            "user_id": "smaueltown@gmail.com",
        },
        {
            "_additional": {
                "answer": {
                    "certainty": None,
                    "endPosition": 0,
                    "hasAnswer": False,
                    "property": None,
                    "result": None,
                    "startPosition": 0,
                },
                "certainty": 0.5469501614570618,
                "id": "0e62a4d5-7637-449d-98ea-c99dac2300f9",
                "score": "0",
            },
            "chunk_text": "THE \nELEMENTS \nOF SLS\nEach major element of SLS – the \ncore stage, RS-25 engines, solid \nrocket boosters, ICPS, Launch \nvehicle stage adapter, and Orion \nstage adapter – serves a unique \npurpose. Each element is built and \ntested by a prime contractor working \nwith numerous subcontractor \nsuppliers. As part of the national \nstrategic infrastructure, SLS is \nbuilt by skilled American engineers \nand technicians at small and large \ncontractor locations across the \nUnited States.\nTHE ELEMENTS OF SLS\n34",
            "user_id": "smaueltown@gmail.com",
        },
    ]
}
